# Generated by Django 2.0.1 on 2018-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_for',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='voter',
            name='vote_value',
            field=models.BooleanField(default=True),
        ),
    ]
