# Generated by Django 2.0.1 on 2018-03-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180227_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_value',
            field=models.BooleanField(default=False),
        ),
    ]
