# Generated by Django 2.0.1 on 2018-05-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_voter_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='contact_number',
            field=models.CharField(max_length=13),
        ),
    ]
